# Generated by Django 4.2.16 on 2024-10-20 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('groups', models.ManyToManyField(to='auth.group')),
                ('permissions', models.OneToOneField(blank=True, limit_choices_to={'codename__in': ['barber', 'customer'], 'content_type__app_label': 'profiles'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.permission')),
            ],
            options={
                'permissions': [('barber', 'Barber Actions'), ('customer', 'Customer Actions')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profiletype', verbose_name='profile_type')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
