# Generated by Django 4.2.16 on 2024-11-08 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('profiles', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profiletype',
            options={'permissions': [('access_to_barber_actions', 'Barber Actions'), ('access_to_customer_actions', 'Customer Actions')]},
        ),
        migrations.AlterField(
            model_name='profiletype',
            name='permissions',
            field=models.OneToOneField(blank=True, limit_choices_to={'codename__in': ['access_to_barber_actions', 'access_to_customer_actions'], 'content_type__app_label': 'profiles'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profiletype', verbose_name='Profile Type'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
