# Generated by Django 4.2.16 on 2024-11-08 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_user_username'),
        ('barbers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber', to='profiles.userprofile'),
        ),
    ]
