# Generated by Django 4.2.16 on 2024-11-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0003_alter_barber_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='name',
            field=models.CharField(default='name', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barber',
            name='shop_name',
            field=models.CharField(default='name', max_length=80),
            preserve_default=False,
        ),
    ]
