# Generated by Django 4.2.16 on 2024-11-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0004_barber_name_barber_shop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
