# Generated by Django 4.2.16 on 2024-10-24 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('barbers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='barber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='barbers.barber'),
        ),
        migrations.AddField(
            model_name='rating',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment'),
        ),
    ]
