# Generated by Django 4.2.16 on 2024-12-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='booked_at',
            new_name='requested_on',
        ),
        migrations.AddField(
            model_name='appointment',
            name='accepted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
