# Generated by Django 4.2.16 on 2024-10-24 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.timeslot'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('date', 'start_time', 'end_time')},
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('profile', 'slot')},
        ),
    ]
