# Generated by Django 4.2.16 on 2024-10-24 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0002_initial'),
        ('appointments', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbers.barber'),
        ),
    ]
