# Generated by Django 4.2.16 on 2024-10-20 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('appointments', '0003_rating_alter_appointment_unique_together_and_more'),
        ('barbers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='barber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='barbers.barber'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('profile', 'slot')},
        ),
        migrations.AddField(
            model_name='rating',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment'),
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
    ]
