# Generated by Django 4.2.16 on 2024-12-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_rename_booked_at_appointment_requested_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='customer_phone_number',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
